version: "3"
services:
  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports: 
      - 27017:27017
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/

  api:
    build: ./api
    ports:
      - 8000:8080
    volumes:
      - ./api:/usr/src/app
    environment:
      NODE_ENV: development
  
  client:
    build: ./client
    ports: 
      - 3000:3000
    volumes:
      - ./client:/usr/src/app