version: "3"
services:
  database:
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    build: ./api
    ports:
      - 8080:8080
    volumes:
      - ./api:/usr/src/app
  
  client:
    build: ./client
    ports: 
      - 3000:3000
    volumes:
      - ./client:/usr/src/app