version: "3"
services:
  database:
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - ./api-documenter-db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    build: ./api-documenter-api
    ports:
      - 8080:8080
    volumes:
      - ./api-documenter-api:/usr/src/app
  
  client:
    build: ./api-documenter-client
    ports: 
      - 80:3000
    volumes:
      - ./api-documenter-client:/usr/src/app